name: Deploying to Tomcat Local

 
 

 
on:

 
push:

 
branches: [ main ]

 
pull_request:

 
branches: [ main ]

 
 

 
jobs:

 
build:

 
name: Deploying to Local Weblogic Server

 
runs-on: self-hosted

 
 

 
steps:

 
#Checking out the code

 
- name: Step-1 Checkout the code

 
uses: actions/checkout@v2

 
 

 
#Build the project with maven build

 
- name: Step-2 Build with Maven

 
run: mvn clean install

 
 

 
#Deploy to Local Weblogic

 
- name: Step-3 Deploy to local Weblogic Server

 
run: mvn weblogic:deploy
